keepkey: bump nanopb to 0.4.9.1
CI fails with:

```
Traceback (most recent call last):
  File "/home/runner/work/HWI/HWI/test/work/keepkey-firmware/nanopb/generator/nanopb_generator.py", line 1816, in <module>
    main_plugin()
  File "/home/runner/work/HWI/HWI/test/work/keepkey-firmware/nanopb/generator/nanopb_generator.py", line 1796, in main_plugin
    other_files[fdesc.name] = parse_file(fdesc.name, fdesc, options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/HWI/HWI/test/work/keepkey-firmware/nanopb/generator/nanopb_generator.py", line 1628, in parse_file
    Globals.separate_options = read_options_file(open(optfilename, "rU"))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
```

https://github.com/bitcoin-core/HWI/actions/runs/16440824447/job/46462763445

This was changed in:
https://github.com/nanopb/nanopb/commit/01e9186a8b8b9856d2438ee2886f3464b9a79f88

That's been in the releases since 0.4.6.